from enum import StrEnum


class AccountStatus(StrEnum):
    ACTIVE = "ACTIVE"
    LOCKED = "LOCKED"
    DISABLED = "DISABLED"


class TradeSessionStatus(StrEnum):
    DRAFT = "DRAFT"
    READY_FOR_ANALYSIS = "READY_FOR_ANALYSIS"
    ANALYZING = "ANALYZING"
    WATCHING = "WATCHING"
    OPEN_POSITION = "OPEN_POSITION"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED_TAKE_PROFIT = "CLOSED_TAKE_PROFIT"
    CLOSED_STOP_LOSS = "CLOSED_STOP_LOSS"
    CLOSED_MANUAL = "CLOSED_MANUAL"
    CANCELLED = "CANCELLED"
    ARCHIVED = "ARCHIVED"


class PositionStatus(StrEnum):
    NOT_OPENED = "NOT_OPENED"
    OPEN = "OPEN"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED = "CLOSED"


class ThesisStatus(StrEnum):
    STRENGTHENING = "STRENGTHENING"
    INTACT = "INTACT"
    INTACT_BUT_WEAKENING = "INTACT_BUT_WEAKENING"
    UNDER_REVIEW = "UNDER_REVIEW"
    INVALIDATED = "INVALIDATED"


class Market(StrEnum):
    IDX = "IDX"
    NASDAQ = "NASDAQ"
    NYSE = "NYSE"
    AMEX = "AMEX"
    OTHER = "OTHER"


class ActionType(StrEnum):
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_CORRECTED = "POSITION_CORRECTED"
    STOP_LOSS_CONFIRMED = "STOP_LOSS_CONFIRMED"
    STOP_LOSS_CHANGED = "STOP_LOSS_CHANGED"
    TARGET_CONFIRMED = "TARGET_CONFIRMED"
    TARGET_CHANGED = "TARGET_CHANGED"
    PARTIAL_EXIT = "PARTIAL_EXIT"
    FULL_EXIT = "FULL_EXIT"
    SESSION_CANCELLED = "SESSION_CANCELLED"
    SESSION_ARCHIVED = "SESSION_ARCHIVED"


class EvidenceType(StrEnum):
    ORDERBOOK_SCREENSHOT = "ORDERBOOK_SCREENSHOT"
    CHART_THREE_MONTH = "CHART_THREE_MONTH"
    CHART_SIX_MONTH = "CHART_SIX_MONTH"
    CHART_DAILY = "CHART_DAILY"
    CHART_INTRADAY = "CHART_INTRADAY"
    BROKER_SUMMARY = "BROKER_SUMMARY"
    FOREIGN_FLOW = "FOREIGN_FLOW"
    NEWS_SCREENSHOT = "NEWS_SCREENSHOT"
    CUSTOM_IMAGE = "CUSTOM_IMAGE"
    USER_NOTE = "USER_NOTE"
    MARKET_DATA_SNAPSHOT = "MARKET_DATA_SNAPSHOT"


class EvidenceStatus(StrEnum):
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    PROCESSING = "PROCESSING"
    UNREADABLE = "UNREADABLE"
    SUPERSEDED = "SUPERSEDED"
    EXCLUDED = "EXCLUDED"
    DUPLICATE = "DUPLICATE"
    FAILED = "FAILED"
    DELETED = "DELETED"


class ExtractionStatus(StrEnum):
    NOT_REQUESTED = "NOT_REQUESTED"
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class Currency(StrEnum):
    IDR = "IDR"
    USD = "USD"
    OTHER = "OTHER"


class AnalysisType(StrEnum):
    INITIAL_ANALYSIS = "INITIAL_ANALYSIS"
    WATCHING_UPDATE = "WATCHING_UPDATE"
    OPEN_POSITION_UPDATE = "OPEN_POSITION_UPDATE"
    PARTIAL_EXIT_REVIEW = "PARTIAL_EXIT_REVIEW"
    CLOSING_ANALYSIS = "CLOSING_ANALYSIS"


class AnalysisJobStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AcceptanceStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ProviderType(StrEnum):
    GEMINI = "GEMINI"
    DEEPSEEK = "DEEPSEEK"
    MOCK = "MOCK"


class ProviderResponseStatus(StrEnum):
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ValidationStage(StrEnum):
    PARSE = "PARSE"
    JSON_SCHEMA = "JSON_SCHEMA"
    DOMAIN = "DOMAIN"
    STATE_CONSISTENCY = "STATE_CONSISTENCY"
    LIFECYCLE = "LIFECYCLE"
    NARRATIVE = "NARRATIVE"


class ValidationResult(StrEnum):
    PENDING = "PENDING"
    VALID = "VALID"
    VALID_WITH_WARNINGS = "VALID_WITH_WARNINGS"
    INVALID = "INVALID"
