from enum import StrEnum


class AccountStatus(StrEnum):
    ACTIVE = "ACTIVE"
    LOCKED = "LOCKED"
    DISABLED = "DISABLED"


class TradeSessionStatus(StrEnum):
    DRAFT = "DRAFT"
    READY_FOR_ANALYSIS = "READY_FOR_ANALYSIS"
    ANALYZING = "ANALYZING"
    WATCHING = "WATCHING"
    OPEN_POSITION = "OPEN_POSITION"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED_TAKE_PROFIT = "CLOSED_TAKE_PROFIT"
    CLOSED_STOP_LOSS = "CLOSED_STOP_LOSS"
    CLOSED_MANUAL = "CLOSED_MANUAL"
    CANCELLED = "CANCELLED"
    ARCHIVED = "ARCHIVED"


class PositionStatus(StrEnum):
    NOT_OPENED = "NOT_OPENED"
    OPEN = "OPEN"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED = "CLOSED"


class ThesisStatus(StrEnum):
    STRENGTHENING = "STRENGTHENING"
    INTACT = "INTACT"
    INTACT_BUT_WEAKENING = "INTACT_BUT_WEAKENING"
    UNDER_REVIEW = "UNDER_REVIEW"
    INVALIDATED = "INVALIDATED"


class Market(StrEnum):
    IDX = "IDX"
    NASDAQ = "NASDAQ"
    NYSE = "NYSE"
    AMEX = "AMEX"
    OTHER = "OTHER"


class ActionType(StrEnum):
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_CORRECTED = "POSITION_CORRECTED"
    STOP_LOSS_CONFIRMED = "STOP_LOSS_CONFIRMED"
    STOP_LOSS_CHANGED = "STOP_LOSS_CHANGED"
    TARGET_CONFIRMED = "TARGET_CONFIRMED"
    TARGET_CHANGED = "TARGET_CHANGED"
    PARTIAL_EXIT = "PARTIAL_EXIT"
    FULL_EXIT = "FULL_EXIT"
    SESSION_CANCELLED = "SESSION_CANCELLED"
    SESSION_ARCHIVED = "SESSION_ARCHIVED"


class Currency(StrEnum):
    IDR = "IDR"
    USD = "USD"
    OTHER = "OTHER"
