"use client";
import { useEffect, useRef, useState } from "react";
import { getSession, readInitialAnalysis, retryInitialAnalysis, submitInitialAnalysis, uploadInitialEvidence } from "./api";
import type { EvidenceFile, InitialAnalysisRead, TradeSession } from "./types";
import { InitialAnalysisResultView } from "./result";

export function SessionWorkspace({ sessionId, knownEvidence, onEvidence }: { sessionId: string; knownEvidence: EvidenceFile[]; onEvidence: (files: EvidenceFile[]) => void }) {
  const [session, setSession] = useState<TradeSession | null>(null); const [analysis, setAnalysis] = useState<InitialAnalysisRead | null>(null); const [files, setFiles] = useState<Record<string, File>>({});
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const inFlight = useRef(false);
  useEffect(() => { let cancelled = false; getSession(sessionId).then(x => { if (!cancelled) setSession(x); }).catch(e => { if (!cancelled) setError(e instanceof Error ? e.message : "Sesi tidak dapat dimuat."); });
    readInitialAnalysis(sessionId).then(x => { if (!cancelled) setAnalysis(x); }).catch(() => { /* no request yet */ }); return () => { cancelled = true; }; }, [sessionId]);
  useEffect(() => { if (!session || !["ANALYZING"].includes(session.status) || analysis?.request_status === "COMPLETED" || analysis?.request_status === "FAILED") return;
    let cancelled = false; let timer: ReturnType<typeof setTimeout>;
    const poll = async () => { if (cancelled || inFlight.current) return; inFlight.current = true; try { const next = await readInitialAnalysis(sessionId); if (!cancelled) { setAnalysis(next); setSession(s => s ? { ...s, status: next.session_status } : s); if (!["COMPLETED", "FAILED"].includes(next.request_status)) timer = setTimeout(poll, 5000); } } catch { if (!cancelled) timer = setTimeout(poll, 5000); } finally { inFlight.current = false; } }; timer = setTimeout(poll, 5000); return () => { cancelled = true; clearTimeout(timer); }; }, [session, sessionId, analysis?.request_status]);
  async function upload(event: React.FormEvent) { event.preventDefault(); if (!files.orderbook || !files.chart_3_month || !files.chart_6_month) { setError("Tiga file evidence wajib dipilih."); return; } setBusy(true); setError(null); try { const response = await uploadInitialEvidence(sessionId, files as { orderbook: File; chart_3_month: File; chart_6_month: File }); onEvidence(response.evidence); } catch (e) { setError(e instanceof Error ? e.message : "Evidence tidak dapat diunggah."); } finally { setBusy(false); } }
  async function submit() { setBusy(true); setError(null); try { const response = await submitInitialAnalysis(sessionId); setAnalysis({ ...response, processed_response: null, error_code: null, error_message: null, started_at: null, completed_at: null }); setSession(s => s ? { ...s, status: response.session_status } : s); } catch (e) { setError(e instanceof Error ? e.message : "Analisis tidak dapat diminta."); } finally { setBusy(false); } }
  async function retry() { setBusy(true); setError(null); try { const response = await retryInitialAnalysis(sessionId); setAnalysis({ ...response, processed_response: null, error_code: null, error_message: null, started_at: null, completed_at: null }); setSession(s => s ? { ...s, status: response.session_status } : s); } catch (e) { setError(e instanceof Error ? e.message : "Analisis tidak dapat dicoba lagi."); } finally { setBusy(false); } }
  if (!session) return <section className="rounded-xl border bg-white p-5">{error ? <p role="alert" className="text-red-700">{error}</p> : "Memuat sesi…"}</section>;
  const completedResult = analysis?.request_status === "COMPLETED" ? analysis.processed_response : null; const complete = completedResult !== null; const failed = analysis?.request_status === "FAILED" || (analysis?.request_status === "PENDING" && session.status === "DRAFT");
  return <section className="space-y-4"><header className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-zinc-500">{session.ticker}</p><h2 className="text-2xl font-bold">{session.company_name}</h2></div><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-semibold">{session.status}</span></div>{session.note && <p className="mt-4 whitespace-pre-wrap text-sm text-zinc-600">{session.note}</p>}</header>
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    {!analysis && session.status === "DRAFT" && knownEvidence.length === 0 && <form onSubmit={upload} className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Evidence Initial Analysis</h3><p className="mt-1 text-sm text-zinc-500">Unggah tepat tiga gambar: order book, grafik 3 bulan, dan grafik 6 bulan.</p><div className="mt-4 grid gap-3">{([["orderbook", "Order Book"], ["chart_3_month", "Grafik 3 Bulan"], ["chart_6_month", "Grafik 6 Bulan"]] as const).map(([key, label]) => <label key={key} className="text-sm font-medium">{label}<input type="file" accept="image/*" required onChange={e => { const file = e.target.files?.[0]; if (file) setFiles(x => ({ ...x, [key]: file })); }} className="mt-1 block w-full text-sm" /></label>)}</div><button disabled={busy} className="mt-4 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy ? "Mengunggah…" : "Unggah Evidence"}</button></form>}
    {knownEvidence.length > 0 && session.status === "DRAFT" && !analysis && <section className="rounded-xl border bg-white p-5"><h3 className="font-semibold">Evidence siap</h3><p className="mt-1 text-sm text-zinc-600">{knownEvidence.length} file diterima.</p><button disabled={busy} onClick={submit} className="mt-4 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy ? "Mengirim…" : "Minta Initial Analysis"}</button></section>}
    {analysis && !complete && !failed && <p className="rounded-xl border bg-white p-5 text-sm text-zinc-700">Analisis sedang diproses. Silakan tunggu.</p>}
    {failed && <section className="rounded-xl border border-red-200 bg-red-50 p-5"><h3 className="font-semibold text-red-900">Initial Analysis gagal diproses</h3><p className="mt-2 text-sm text-red-800">{analysis?.error_message || "Permintaan analisis belum masuk ke pemrosesan."}</p><button disabled={busy} onClick={retry} className="mt-4 rounded-lg bg-red-700 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy ? "Mencoba…" : "Coba Lagi"}</button></section>}
    {completedResult && <InitialAnalysisResultView result={completedResult} />}
  </section>;
}
