"""analysis models

Revision ID: fc58b8bbeab7
Revises: 9d219c5a02e1
Create Date: 2026-07-18 07:13:46.409031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc58b8bbeab7'
down_revision: Union[str, Sequence[str], None] = '9d219c5a02e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.Enum('INITIAL_ANALYSIS', 'WATCHING_UPDATE', 'OPEN_POSITION_UPDATE', 'PARTIAL_EXIT_REVIEW', 'CLOSING_ANALYSIS', name='analysis_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'PROCESSING', 'RETRYING', 'COMPLETED', 'FAILED', 'CANCELLED', name='analysis_job_status_enum'), server_default=sa.text("'CREATED'::analysis_job_status_enum"), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_session_status', sa.String(length=32), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count <= max_attempts', name=op.f('ck_analysis_jobs_attempts_bound')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_analysis_jobs_attempt_count')),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_analysis_jobs_max_attempts')),
    sa.ForeignKeyConstraint(['session_id'], ['trade_sessions.id'], name=op.f('fk_analysis_jobs_session_id_trade_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    op.create_index('ix_analysis_jobs_lease', 'analysis_jobs', ['status', 'lease_expires_at'], unique=False)
    op.create_index('ix_analysis_jobs_queue', 'analysis_jobs', ['status', 'available_at'], unique=False)
    op.create_index('ix_analysis_jobs_session_created', 'analysis_jobs', ['session_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_analysis_jobs_session_id'), 'analysis_jobs', ['session_id'], unique=False)
    op.create_index('ix_analysis_jobs_session_type_status', 'analysis_jobs', ['session_id', 'analysis_type', 'status'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=True),
    sa.Column('analysis_type', sa.Enum('INITIAL_ANALYSIS', 'WATCHING_UPDATE', 'OPEN_POSITION_UPDATE', 'PARTIAL_EXIT_REVIEW', 'CLOSING_ANALYSIS', name='analysis_type_enum'), nullable=False),
    sa.Column('acceptance_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'SUPERSEDED', name='acceptance_status_enum'), server_default=sa.text("'PENDING'::acceptance_status_enum"), nullable=False),
    sa.Column('prompt_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_analysis_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("prompt_name IS NOT NULL AND BTRIM(prompt_name) <> ''", name=op.f('ck_analyses_prompt_name')),
    sa.CheckConstraint("prompt_version IS NOT NULL AND BTRIM(prompt_version) <> ''", name=op.f('ck_analyses_prompt_version')),
    sa.CheckConstraint("schema_name IS NOT NULL AND BTRIM(schema_name) <> ''", name=op.f('ck_analyses_schema_name')),
    sa.CheckConstraint("schema_version IS NOT NULL AND BTRIM(schema_version) <> ''", name=op.f('ck_analyses_schema_version')),
    sa.CheckConstraint('supersedes_analysis_id IS NULL OR supersedes_analysis_id <> id', name=op.f('ck_analyses_no_self_supersede')),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], name=op.f('fk_analyses_analysis_job_id_analysis_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['trade_sessions.id'], name=op.f('fk_analyses_session_id_trade_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_analysis_id'], ['analyses.id'], name=op.f('fk_analyses_supersedes_analysis_id_analyses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index('ix_analyses_accepted', 'analyses', ['session_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text("acceptance_status = 'ACCEPTED'"))
    op.create_index('ix_analyses_job', 'analyses', ['analysis_job_id'], unique=False)
    op.create_index(op.f('ix_analyses_session_id'), 'analyses', ['session_id'], unique=False)
    op.create_index('ix_analyses_session_type_created', 'analyses', ['session_id', 'analysis_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_analyses_supersedes', 'analyses', ['supersedes_analysis_id'], unique=False)
    op.create_table('provider_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GEMINI', 'DEEPSEEK', 'MOCK', name='provider_enum'), nullable=False),
    sa.Column('provider_model', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('prompt_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("prompt_name IS NOT NULL AND BTRIM(prompt_name) <> ''", name=op.f('ck_provider_requests_prompt_name')),
    sa.CheckConstraint("prompt_version IS NOT NULL AND BTRIM(prompt_version) <> ''", name=op.f('ck_provider_requests_prompt_version')),
    sa.CheckConstraint("schema_name IS NOT NULL AND BTRIM(schema_name) <> ''", name=op.f('ck_provider_requests_schema_name')),
    sa.CheckConstraint("schema_version IS NOT NULL AND BTRIM(schema_version) <> ''", name=op.f('ck_provider_requests_schema_version')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_provider_requests_attempt_number')),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], name=op.f('fk_provider_requests_analysis_job_id_analysis_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_requests'))
    )
    op.create_index(op.f('ix_provider_requests_analysis_job_id'), 'provider_requests', ['analysis_job_id'], unique=False)
    op.create_table('provider_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_request_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='provider_response_status_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_response_id', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('finish_reason', sa.String(length=64), nullable=True),
    sa.Column('usage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_provider_responses_input_tokens')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_provider_responses_latency')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_provider_responses_output_tokens')),
    sa.CheckConstraint('total_tokens IS NULL OR total_tokens >= 0', name=op.f('ck_provider_responses_total_tokens')),
    sa.ForeignKeyConstraint(['provider_request_id'], ['provider_requests.id'], name=op.f('fk_provider_responses_provider_request_id_provider_requests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_responses'))
    )
    op.create_index(op.f('ix_provider_responses_provider_request_id'), 'provider_responses', ['provider_request_id'], unique=False)
    op.create_table('validation_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('provider_response_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('stage', sa.Enum('PARSE', 'JSON_SCHEMA', 'DOMAIN', 'STATE_CONSISTENCY', 'LIFECYCLE', 'NARRATIVE', name='validation_stage_enum'), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_validation_attempts_attempt_number')),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], name=op.f('fk_validation_attempts_analysis_job_id_analysis_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_response_id'], ['provider_responses.id'], name=op.f('fk_validation_attempts_provider_response_id_provider_responses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_attempts'))
    )
    op.create_index(op.f('ix_validation_attempts_analysis_job_id'), 'validation_attempts', ['analysis_job_id'], unique=False)
    # Clear orphaned related_analysis_id before adding FK
    op.execute("UPDATE trade_actions SET related_analysis_id = NULL WHERE related_analysis_id IS NOT NULL")
    op.create_foreign_key(op.f('fk_trade_actions_related_analysis_id_analyses'), 'trade_actions', 'analyses', ['related_analysis_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_trade_actions_related_analysis_id_analyses'), 'trade_actions', type_='foreignkey')
    op.drop_index(op.f('ix_validation_attempts_analysis_job_id'), table_name='validation_attempts')
    op.drop_table('validation_attempts')
    op.drop_index(op.f('ix_provider_responses_provider_request_id'), table_name='provider_responses')
    op.drop_table('provider_responses')
    op.drop_index(op.f('ix_provider_requests_analysis_job_id'), table_name='provider_requests')
    op.drop_table('provider_requests')
    op.drop_index('ix_analyses_supersedes', table_name='analyses')
    op.drop_index('ix_analyses_session_type_created', table_name='analyses')
    op.drop_index(op.f('ix_analyses_session_id'), table_name='analyses')
    op.drop_index('ix_analyses_job', table_name='analyses')
    op.drop_index('ix_analyses_accepted', table_name='analyses', postgresql_where=sa.text("acceptance_status = 'ACCEPTED'"))
    op.drop_table('analyses')
    op.drop_index('ix_analysis_jobs_session_type_status', table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_session_id'), table_name='analysis_jobs')
    op.drop_index('ix_analysis_jobs_session_created', table_name='analysis_jobs')
    op.drop_index('ix_analysis_jobs_queue', table_name='analysis_jobs')
    op.drop_index('ix_analysis_jobs_lease', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.execute("DROP TYPE IF EXISTS analysis_type_enum")
    op.execute("DROP TYPE IF EXISTS analysis_job_status_enum")
    op.execute("DROP TYPE IF EXISTS acceptance_status_enum")
    op.execute("DROP TYPE IF EXISTS provider_enum")
    op.execute("DROP TYPE IF EXISTS provider_response_status_enum")
    op.execute("DROP TYPE IF EXISTS validation_stage_enum")
    # ### end Alembic commands ###
